/**
 * tauron plugin — 插件管理命令
 *
 * 子命令：new/dev/test/pack/sign/publish
 */

import type { PluginConfig, PackageManifest, CliOptions, PluginType } from './types.js';

/**
 * 创建新插件
 */
export function pluginNew(config: PluginConfig, options: CliOptions): PluginCreateResult {
  const files: Record<string, string> = {};
  const manifest = generatePluginManifest(config);

  // package.json
  files['package.json'] = JSON.stringify(manifest, null, 2);

  // Entry file based on type
  if (config.type === 'js') {
    files['src/index.js'] = generateJsPlugin(config);
  } else if (config.type === 'wasm') {
    files['src/index.js'] = generateJsPlugin(config);
    files['Cargo.toml'] = generateWasmCargo(config);
    files['src/lib.rs'] = generateWasmRust(config);
  } else if (config.type === 'process') {
    files['src/index.js'] = generateJsPlugin(config);
    files['main.js'] = generateProcessPlugin(config);
  }

  // README
  files['README.md'] = generatePluginReadme(config);

  return { files, manifest, dirName: config.name };
}

export interface PluginCreateResult {
  files: Record<string, string>;
  manifest: PackageManifest;
  dirName: string;
}

/**
 * 生成插件 package.json
 */
export function generatePluginManifest(config: PluginConfig): PackageManifest {
  return {
    name: config.name,
    version: '0.1.0',
    description: config.description ?? `tauron plugin: ${config.name}`,
    type: config.type,
    main: config.type === 'process' ? 'main.js' : 'src/index.js',
    permissions: config.permissions ?? ['store:read', 'http:fetch'],
    devDependencies: {
      '@tauron/plugin-sdk': '^0.1.0',
    },
  };
}

/**
 * 生成 JS 插件入口
 */
function generateJsPlugin(config: PluginConfig): string {
  const methods = (config.permissions ?? []).map((p) => {
    const methodName = p.replace(/:/g, '_');
    return `  ${methodName}({ args, ctx }) {
    return { result: 'OK' };
  },`;
  });

  return `// ${config.name} — tauron plugin
// Generated by tauron plugin new

import { registerPlugin } from '@tauron/plugin-sdk';

registerPlugin({
  name: '${config.name}',
  version: '0.1.0',
  methods: {
${methods.join('\n')}
  },
  events: {},
  onEnable(ctx) {
    console.log('[${config.name}] enabled');
  },
  onDisable(ctx) {
    console.log('[${config.name}] disabled');
  },
});
`;
}

/**
 * 生成 WASM Cargo.toml
 */
function generateWasmCargo(config: PluginConfig): string {
  return `[package]
name = "${config.name.replace(/-/g, '_')}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tauron-wasm = "0.1"
`;
}

/**
 * 生成 WASM Rust 入口
 */
function generateWasmRust(config: PluginConfig): string {
  const name = config.name.replace(/-/g, '_');
  return `use tauron_wasm::plugin;

#[plugin]
fn ${name}() -> Result<(), String> {
    Ok(())
}
`;
}

/**
 * 生成进程插件入口
 */
function generateProcessPlugin(config: PluginConfig): string {
  return `// ${config.name} — tauron process plugin
// Generated by tauron plugin new

const { createServer } = require('net');

const server = createServer((socket) => {
  socket.on('data', (data) => {
    const request = JSON.parse(data.toString());
    const response = handleRequest(request);
    socket.write(JSON.stringify(response) + '\\n');
  });
});

function handleRequest(request) {
  const { id, method, params } = request;
  let result;
  try {
    result = handleMethod(method, params);
  } catch (error) {
    return { id, error: error.message };
  }
  return { id, result };
}

function handleMethod(method, params) {
  switch (method) {
    case 'ping':
      return { pong: true };
    default:
      throw new Error(\`Unknown method: \${method}\`);
  }
}

server.listen(0, () => {
  console.log(\`Plugin ${config.name} listening on port \${server.address().port}\`);
});
`;
}

/**
 * 生成插件 README
 */
function generatePluginReadme(config: PluginConfig): string {
  return `# ${config.name}

${config.description ?? `tauron plugin: ${config.name}`}

## Type

\`${config.type}\`

## Permissions

${(config.permissions ?? []).map((p) => `- \`${p}\``).join('\n')}

## Usage

\`\`\`js
import { usePlugin } from '@tauron/plugin-sdk';
const plugin = usePlugin('${config.name}');
\`\`\`
`;
}
